# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interface.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_principale_ihm(object):
    def setupUi(self, principale_ihm):
        principale_ihm.setObjectName("principale_ihm")
        principale_ihm.resize(800, 600)
        principale_ihm.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Icône jeu.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        principale_ihm.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(principale_ihm)
        self.centralwidget.setObjectName("centralwidget")
        self.conteneur = QtWidgets.QWidget(self.centralwidget)
        self.conteneur.setGeometry(QtCore.QRect(40, 10, 451, 331))
        self.conteneur.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.conteneur.setObjectName("conteneur")
        self.CarteJ1 = QtWidgets.QWidget(self.conteneur)
        self.CarteJ1.setGeometry(QtCore.QRect(200, 230, 51, 81))
        self.CarteJ1.setCursor(QtGui.QCursor(QtCore.Qt.ClosedHandCursor))
        self.CarteJ1.setObjectName("CarteJ1")
        self.CarteJ3 = QtWidgets.QWidget(self.conteneur)
        self.CarteJ3.setGeometry(QtCore.QRect(200, 50, 51, 81))
        self.CarteJ3.setCursor(QtGui.QCursor(QtCore.Qt.ForbiddenCursor))
        self.CarteJ3.setObjectName("CarteJ3")
        self.CarteJ2 = QtWidgets.QWidget(self.conteneur)
        self.CarteJ2.setGeometry(QtCore.QRect(60, 150, 91, 51))
        self.CarteJ2.setCursor(QtGui.QCursor(QtCore.Qt.ForbiddenCursor))
        self.CarteJ2.setObjectName("CarteJ2")
        self.CarteJ4 = QtWidgets.QWidget(self.conteneur)
        self.CarteJ4.setGeometry(QtCore.QRect(300, 150, 91, 51))
        self.CarteJ4.setCursor(QtGui.QCursor(QtCore.Qt.ForbiddenCursor))
        self.CarteJ4.setObjectName("CarteJ4")
        self.Joueur3 = QtWidgets.QWidget(self.conteneur)
        self.Joueur3.setGeometry(QtCore.QRect(210, 10, 31, 31))
        self.Joueur3.setObjectName("Joueur3")
        self.Joueur4 = QtWidgets.QWidget(self.conteneur)
        self.Joueur4.setGeometry(QtCore.QRect(410, 160, 31, 31))
        self.Joueur4.setObjectName("Joueur4")
        self.Joueur2 = QtWidgets.QWidget(self.conteneur)
        self.Joueur2.setGeometry(QtCore.QRect(20, 160, 31, 31))
        self.Joueur2.setObjectName("Joueur2")
        self.ScoreJ1 = QtWidgets.QLCDNumber(self.conteneur)
        self.ScoreJ1.setGeometry(QtCore.QRect(10, 280, 64, 23))
        self.ScoreJ1.setObjectName("ScoreJ1")
        self.ScoreJ2 = QtWidgets.QLCDNumber(self.conteneur)
        self.ScoreJ2.setGeometry(QtCore.QRect(13, 120, 71, 23))
        self.ScoreJ2.setObjectName("ScoreJ2")
        self.ScoreJ3 = QtWidgets.QLCDNumber(self.conteneur)
        self.ScoreJ3.setGeometry(QtCore.QRect(260, 10, 64, 23))
        self.ScoreJ3.setObjectName("ScoreJ3")
        self.ScoreJ4 = QtWidgets.QLCDNumber(self.conteneur)
        self.ScoreJ4.setGeometry(QtCore.QRect(370, 120, 64, 23))
        self.ScoreJ4.setObjectName("ScoreJ4")
        self.label = QtWidgets.QLabel(self.conteneur)
        self.label.setGeometry(QtCore.QRect(10, 250, 51, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.BetFiller = QtWidgets.QSpinBox(self.conteneur)
        self.BetFiller.setGeometry(QtCore.QRect(400, 280, 42, 22))
        self.BetFiller.setObjectName("BetFiller")
        self.label_2 = QtWidgets.QLabel(self.conteneur)
        self.label_2.setGeometry(QtCore.QRect(410, 250, 35, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.ScoresetJ1 = QtWidgets.QLCDNumber(self.conteneur)
        self.ScoresetJ1.setGeometry(QtCore.QRect(200, 200, 51, 20))
        self.ScoresetJ1.setObjectName("ScoresetJ1")
        self.ScoresetlJ3 = QtWidgets.QLCDNumber(self.conteneur)
        self.ScoresetlJ3.setGeometry(QtCore.QRect(200, 130, 51, 20))
        self.ScoresetlJ3.setObjectName("ScoresetlJ3")
        self.ScoresetJ2 = QtWidgets.QLCDNumber(self.conteneur)
        self.ScoresetJ2.setGeometry(QtCore.QRect(160, 160, 51, 20))
        self.ScoresetJ2.setObjectName("ScoresetJ2")
        self.ScoresetlJ4 = QtWidgets.QLCDNumber(self.conteneur)
        self.ScoresetlJ4.setGeometry(QtCore.QRect(240, 160, 51, 20))
        self.ScoresetlJ4.setObjectName("ScoresetlJ4")
        self.CarteJ1_2 = QtWidgets.QWidget(self.conteneur)
        self.CarteJ1_2.setGeometry(QtCore.QRect(250, 230, 51, 81))
        self.CarteJ1_2.setCursor(QtGui.QCursor(QtCore.Qt.ClosedHandCursor))
        self.CarteJ1_2.setObjectName("CarteJ1_2")
        self.CarteJ1_3 = QtWidgets.QWidget(self.conteneur)
        self.CarteJ1_3.setGeometry(QtCore.QRect(300, 230, 51, 81))
        self.CarteJ1_3.setCursor(QtGui.QCursor(QtCore.Qt.ClosedHandCursor))
        self.CarteJ1_3.setObjectName("CarteJ1_3")
        self.CarteJ1_4 = QtWidgets.QWidget(self.conteneur)
        self.CarteJ1_4.setGeometry(QtCore.QRect(150, 230, 51, 81))
        self.CarteJ1_4.setCursor(QtGui.QCursor(QtCore.Qt.ClosedHandCursor))
        self.CarteJ1_4.setObjectName("CarteJ1_4")
        self.CarteJ1_5 = QtWidgets.QWidget(self.conteneur)
        self.CarteJ1_5.setGeometry(QtCore.QRect(100, 230, 51, 81))
        self.CarteJ1_5.setCursor(QtGui.QCursor(QtCore.Qt.ClosedHandCursor))
        self.CarteJ1_5.setObjectName("CarteJ1_5")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(49, 350, 431, 22))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Restart = QtWidgets.QPushButton(self.layoutWidget)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("Icône recommencer.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Restart.setIcon(icon1)
        self.Restart.setObjectName("Restart")
        self.horizontalLayout.addWidget(self.Restart)
        spacerItem = QtWidgets.QSpacerItem(318, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.Leave = QtWidgets.QPushButton(self.layoutWidget)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("Icône quitter.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Leave.setIcon(icon2)
        self.Leave.setObjectName("Leave")
        self.horizontalLayout.addWidget(self.Leave)
        principale_ihm.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(principale_ihm)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 18))
        self.menubar.setObjectName("menubar")
        self.menuMenu = QtWidgets.QMenu(self.menubar)
        self.menuMenu.setObjectName("menuMenu")
        principale_ihm.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(principale_ihm)
        self.statusbar.setObjectName("statusbar")
        principale_ihm.setStatusBar(self.statusbar)
        self.actionQuitter = QtWidgets.QAction(principale_ihm)
        self.actionQuitter.setObjectName("actionQuitter")
        self.actionRegles = QtWidgets.QAction(principale_ihm)
        self.actionRegles.setObjectName("actionRegles")
        self.menuMenu.addSeparator()
        self.menuMenu.addAction(self.actionQuitter)
        self.menuMenu.addAction(self.actionRegles)
        self.menubar.addAction(self.menuMenu.menuAction())

        self.retranslateUi(principale_ihm)
        self.actionQuitter.triggered.connect(principale_ihm.close)
        self.Leave.clicked.connect(principale_ihm.close)
        QtCore.QMetaObject.connectSlotsByName(principale_ihm)

    def retranslateUi(self, principale_ihm):
        _translate = QtCore.QCoreApplication.translate
        principale_ihm.setWindowTitle(_translate("principale_ihm", "MenuPrincipal"))
        self.label.setText(_translate("principale_ihm", "Score"))
        self.label_2.setText(_translate("principale_ihm", "Bet"))
        self.Restart.setText(_translate("principale_ihm", "Start again"))
        self.Restart.setShortcut(_translate("principale_ihm", "Ctrl+R"))
        self.Leave.setText(_translate("principale_ihm", "Leave"))
        self.Leave.setShortcut(_translate("principale_ihm", "Ctrl+Q"))
        self.menuMenu.setTitle(_translate("principale_ihm", "Menu"))
        self.actionQuitter.setText(_translate("principale_ihm", "Leave"))
        self.actionQuitter.setShortcut(_translate("principale_ihm", "Ctrl+Q"))
        self.actionRegles.setText(_translate("principale_ihm", "Rules"))
        self.actionRegles.setShortcut(_translate("principale_ihm", "Ctrl+F"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    principale_ihm = QtWidgets.QMainWindow()
    ui = Ui_principale_ihm()
    ui.setupUi(principale_ihm)
    principale_ihm.show()
    sys.exit(app.exec_())

